use crate::engine::types::AIStyle;

pub struct StyleWeights {
    pub capture_mult: f64,
    pub atari_weight: f64,
    pub self_atari_penalty: f64,
    pub connection_weight: f64,
    pub center_weight: f64,
    pub edge_penalty_first: f64,
    pub edge_penalty_second: f64,
    pub noise_scale: f64,
    pub proximity_weight: f64,
    pub territory_weight: f64,
    pub capture_threshold: f64,
    pub base_atari_bonus: f64,
    pub base_capture_bonus: f64,
    pub connection_bonus_per: f64,
    pub eye_penalty: f64,
    pub ladder_bonus: f64,
    pub influence_weight: f64,
    pub group_health_weight: f64,
    pub shape_weight: f64,
}

pub fn get_style_weights(style: AIStyle) -> StyleWeights {
    match style {
        AIStyle::Balanced => StyleWeights {
            capture_mult: 15.0,
            atari_weight: 8.0,
            self_atari_penalty: -12.0,
            connection_weight: 3.0,
            center_weight: 0.5,
            edge_penalty_first: -4.0,
            edge_penalty_second: -1.0,
            noise_scale: 1.5,
            proximity_weight: 0.0,
            territory_weight: 0.0,
            capture_threshold: 0.7,
            base_atari_bonus: 4.0,
            base_capture_bonus: 10.0,
            connection_bonus_per: 0.1,
            eye_penalty: -20.0,
            ladder_bonus: 50.0,
            influence_weight: 0.3,
            group_health_weight: 0.5,
            shape_weight: 1.0,
        },
        AIStyle::Aggressive => StyleWeights {
            capture_mult: 25.0,
            atari_weight: 15.0,
            self_atari_penalty: -6.0,
            connection_weight: 2.0,
            center_weight: 0.3,
            edge_penalty_first: -2.0,
            edge_penalty_second: 0.0,
            noise_scale: 2.0,
            proximity_weight: 3.0,
            territory_weight: 0.0,
            capture_threshold: 0.9,
            base_atari_bonus: 4.0,
            base_capture_bonus: 10.0,
            connection_bonus_per: 0.1,
            eye_penalty: -15.0,
            ladder_bonus: 60.0,
            influence_weight: 0.2,
            group_health_weight: 0.3,
            shape_weight: 0.5,
        },
        AIStyle::Defensive => StyleWeights {
            capture_mult: 8.0,
            atari_weight: 4.0,
            self_atari_penalty: -20.0,
            connection_weight: 8.0,
            center_weight: 0.4,
            edge_penalty_first: -6.0,
            edge_penalty_second: -2.0,
            noise_scale: 1.0,
            proximity_weight: -1.0,
            territory_weight: 2.0,
            capture_threshold: 0.5,
            base_atari_bonus: 4.0,
            base_capture_bonus: 10.0,
            connection_bonus_per: 0.1,
            eye_penalty: -25.0,
            ladder_bonus: 40.0,
            influence_weight: 0.4,
            group_health_weight: 0.8,
            shape_weight: 1.5,
        },
        AIStyle::Educational => StyleWeights {
            capture_mult: 12.0,
            atari_weight: 6.0,
            self_atari_penalty: -14.0,
            connection_weight: 4.0,
            center_weight: 0.5,
            edge_penalty_first: -4.0,
            edge_penalty_second: -1.0,
            noise_scale: 1.0,
            proximity_weight: 0.0,
            territory_weight: 0.5,
            capture_threshold: 0.7,
            base_atari_bonus: 4.0,
            base_capture_bonus: 10.0,
            connection_bonus_per: 0.1,
            eye_penalty: -22.0,
            ladder_bonus: 55.0,
            influence_weight: 0.35,
            group_health_weight: 0.6,
            shape_weight: 1.2,
        },
    }
}
